# Generated by Django 3.2 on 2023-09-09 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aboutpage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('content', models.TextField(blank=True, max_length=700)),
                ('image', models.ImageField(blank=True, upload_to='aboutpage/%Y/%m/%d')),
                ('image1', models.ImageField(blank=True, upload_to='aboutpage/%Y/%m/%d')),
                ('aboutus', models.TextField(blank=True, max_length=500)),
                ('aboutimage', models.ImageField(blank=True, upload_to='aboutpage/%Y/%m/%d')),
                ('project', models.TextField(blank=True, max_length=500)),
                ('projectimage', models.ImageField(blank=True, upload_to='aboutpage/%Y/%m/%d')),
                ('story', models.TextField(blank=True, max_length=1500)),
                ('storyimage', models.ImageField(blank=True, upload_to='aboutpage/%Y/%m/%d')),
                ('team', models.TextField(blank=True, max_length=1500)),
                ('teamimage', models.ImageField(blank=True, upload_to='aboutpage/%Y/%m/%d')),
                ('whyus', models.TextField(blank=True, max_length=1500)),
                ('whyusimage', models.ImageField(blank=True, upload_to='aboutpage/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='Create',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bizname', models.CharField(max_length=200)),
                ('Location', models.TextField()),
                ('Phone', models.CharField(max_length=14)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(max_length=500)),
                ('image1', models.ImageField(null=True, upload_to='posts/%Y/%m/%d')),
                ('date', models.DateTimeField(auto_now=True)),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_posts', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
